### ISSUE TITLE
Notifiarr Compose - Invalid Env Vars

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides-Synology-Templates#151]
https://github.com/TRaSH-/Guides-Synology-Templates/blob/1c280bf06b3137a853b6800e164b2b6be21256c7/templates/notifiarr.yml#L20-L21

@BaukeZwart that update to add PUID/GUID should have never been made. GoLift Containers do not support PUID/PGUID

needs to be `user: ${PUID}:${PGID}`

**Comment by BaukeZwart** [comment]
I will rever it when I'm home.
Thanks for the heads up.

**Comment by bokkoman** [comment]
reverted
