### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sveinbjornpalsson** [TRaSH-/Guides-Synology-Templates#167]
**Which Template**
Please add which in which Template you found a Bug/Error with.
[Guides-Synology-Templates](https://github.com/TRaSH-/Guides-Synology-Templates/tree/main)/[templates](https://github.com/TRaSH-/Guides-Synology-Templates/tree/main/templates)
/readarr.yml
**Describe the Bug/Error in the Template**
First word in the template: it says # Bazarr, not # Readarr.
**Additional context**
very minor error.

**Comment by bokkoman** [comment]
Why not PR it?

**Comment by bokkoman** [comment]
> Didn't know to do that. Never done that. But I did try editing it myself. I'll do a pull request next time :)

That would be better :D
